#services:
#  prometheus_check_item.create_check_item:
#    path: 'api/check_item/create'
#    defaults:
#      _controller: '\Drupal\prometheus_check_item\Controller\CustomRestController::getLatestNodes'
#    methods: [POST]
#    requirements:
#      _access: 'TRUE'
