<?php

/**
 * @file
 * Primary module hooks for prometheus_check_item module.
 */

use Google\Cloud\PubSub\MessageBuilder;
use Google\Cloud\PubSub\PubSubClient;

/**
 * Implements hook_cron().
 */
function prometheus_check_item_cron() {

}

function _trigger_checks_default() {
  try {
    /** @var \Drupal\prometheus_check_item\TriggerCheck $triggerCheckService */
    $triggerCheckService = \Drupal::service('prometheus_check_item.trigger_check');
    $triggerCheckService->trigger('default');
  }
  catch (\Exception $exception) {
    $msg = $exception->getMessage();
    \Drupal::logger('test')->error($msg);
  }

}

function _evaluate_checks() {
  try {
    /** @var \Drupal\prometheus_check_item\EvaluateChecks $evaluateCheckService */
    $evaluateCheckService = \Drupal::service('prometheus_check_item.evaluate_checks');
    $evaluateCheckService->evaluate();
  }
  catch (\Exception $exception) {
    $msg = $exception->getMessage();
    \Drupal::logger('test')->error($msg);
  }
}